# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flow/access/access.proto for package 'access'

require 'grpc'
require 'flow/access/access_pb'

module Access
  module AccessAPI
    # AccessAPI is the public-facing API provided by access nodes.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'access.AccessAPI'

      # Ping is used to check if the access node is alive and healthy.
      rpc :Ping, PingRequest, PingResponse
      # Block Headers
      #
      # GetLatestBlockHeader gets the latest sealed or unsealed block header.
      rpc :GetLatestBlockHeader, GetLatestBlockHeaderRequest, BlockHeaderResponse
      # GetBlockHeaderByID gets a block header by ID.
      rpc :GetBlockHeaderByID, GetBlockHeaderByIDRequest, BlockHeaderResponse
      # GetBlockHeaderByHeight gets a block header by height.
      rpc :GetBlockHeaderByHeight, GetBlockHeaderByHeightRequest, BlockHeaderResponse
      # Blocks
      #
      # GetLatestBlock gets the full payload of the latest sealed or unsealed block.
      rpc :GetLatestBlock, GetLatestBlockRequest, BlockResponse
      # GetBlockByID gets a full block by ID.
      rpc :GetBlockByID, GetBlockByIDRequest, BlockResponse
      # GetBlockByHeight gets a full block by height.
      rpc :GetBlockByHeight, GetBlockByHeightRequest, BlockResponse
      # Collections
      #
      # GetCollectionByID gets a collection by ID.
      rpc :GetCollectionByID, GetCollectionByIDRequest, CollectionResponse
      # Transactions
      #
      # SendTransaction submits a transaction to the network.
      rpc :SendTransaction, SendTransactionRequest, SendTransactionResponse
      # GetTransaction gets a transaction by ID.
      rpc :GetTransaction, GetTransactionRequest, TransactionResponse
      # GetTransactionResult gets the result of a transaction.
      rpc :GetTransactionResult, GetTransactionRequest, TransactionResultResponse
      # Accounts
      #
      # GetAccountAtLatestBlock gets an account by address from the latest sealed execution state.
      rpc :GetAccountAtLatestBlock, GetAccountAtLatestBlockRequest, AccountResponse
      # GetAccountAtBlockHeight gets an account by address at the given block height
      rpc :GetAccountAtBlockHeight, GetAccountAtBlockHeightRequest, AccountResponse
      # Scripts
      #
      # ExecuteScriptAtLatestBlock executes a read-only Cadence script against the latest sealed execution state.
      rpc :ExecuteScriptAtLatestBlock, ExecuteScriptAtLatestBlockRequest, ExecuteScriptResponse
      # ExecuteScriptAtBlockID executes a ready-only Cadence script against the execution state at the block with the given ID.
      rpc :ExecuteScriptAtBlockID, ExecuteScriptAtBlockIDRequest, ExecuteScriptResponse
      # ExecuteScriptAtBlockHeight executes a ready-only Cadence script against the execution state at the given block height.
      rpc :ExecuteScriptAtBlockHeight, ExecuteScriptAtBlockHeightRequest, ExecuteScriptResponse
      # Events
      #
      # GetEventsForHeightRange retrieves events emitted within the specified block range.
      rpc :GetEventsForHeightRange, GetEventsForHeightRangeRequest, EventsResponse
      # GetEventsForBlockIDs retrieves events for the specified block IDs and event type.
      rpc :GetEventsForBlockIDs, GetEventsForBlockIDsRequest, EventsResponse
      # NetworkParameters
      #
      # GetNetworkParameters retrieves the Flow network details
      rpc :GetNetworkParameters, GetNetworkParametersRequest, GetNetworkParametersResponse
    end

    Stub = Service.rpc_stub_class
  end
end
